-- Generated by Mocodo 4.2.1

-- Création de la base de données
CREATE DATABASE IF NOT EXISTS cinefiles;

-- Utilisation de la base de données
USE cinefiles;

-- Création de la table acteurs
CREATE TABLE IF NOT EXISTS acteurs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  nom        VARCHAR(50),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Création de la table categories
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  nom        VARCHAR(50),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Création de la table realisateurs
CREATE TABLE IF NOT EXISTS realisateurs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  nom        VARCHAR(50),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Création de la table films
CREATE TABLE IF NOT EXISTS films (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  cat_id BIGINT UNSIGNED,
  FOREIGN KEY (cat_id) REFERENCES categories (id) ON DELETE SET NULL,
  real_id BIGINT UNSIGNED,
  FOREIGN KEY (real_id) REFERENCES realisateurs (id) ON DELETE SET NULL,
  nom        VARCHAR(50),
  extrait    VARCHAR(300),
  pitch      TEXT NOT NULL,
  affiche    VARCHAR(150),
  annee      BIGINT,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Création de la table intermédiaire jouentDans ( gestion relation many to many entre les tables films et acteurs)
CREATE TABLE IF NOT EXISTS jouentDans (
  film_id BIGINT UNSIGNED NOT NULL,
  acteur_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (film_id, acteur_id),
  FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
  FOREIGN KEY (acteur_id) REFERENCES acteurs (id) ON DELETE CASCADE
);

